---
driver:
  name: vagrant

transport:
  name: winrm
  winrm_transport: plaintext
  
provisioner:
  name: chef_solo

platforms:
  - name: windows-2012r2
    driver:
      box: jason/Windows2012R2
      customize:
        memory: 2048

suites:
  - name: server
    driver:
      network:
        - ["private_network", {ip: "192.168.50.12"}]
    run_list:
      - recipe[nuget::bootstrap_module]
      - recipe[bits_server::default]
    attributes:
